Develop pod-interface plugin

diff --git a/bin/kubectl-pod-interface b/bin/kubectl-pod-interface
--- a/bin/kubectl-pod-interface
+++ b/bin/kubectl-pod-interface
@@ -1,18 +1,18 @@
 #!/bin/bash
 
-#Copyright © 2021 Aymen Segni segniaymen1@gmail.com
+# Copyright © 2021 Aymen Segni segniaymen1@gmail.com
 
-#Licensed under the Apache License, Version 2.0 (the "License");
-#you may not use this file except in compliance with the License.
-#You may obtain a copy of the License at
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
 #
 #    http://www.apache.org/licenses/LICENSE-2.0
 #
-#Unless required by applicable law or agreed to in writing, software
-#distributed under the License is distributed on an "AS IS" BASIS,
-#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-#See the License for the specific language governing permissions and
-#limitations under the License.
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
 
 # See usage().
 
@@ -21,55 +21,70 @@
 set -eou pipefail
 IFS=$'\n\t'
 
+NOW=$(date +"%F")
+NOWT=$(date +"%T")
+APPDIR="${HOME}"/.kubectl-pod-interface
+DAEMONSFILE="${APPDIR}"/kubectl-pod-interfaced
+LOGFILE=${APPDIR}/kubectl-pod-interface-${NOW}-${NOWT}.log
+
+
+# source scripts
+# for f in ${BASH_SOURCE[0]}/bin/*
+#
+# do source $f 
+# 
+# done
+
+source kubectl-pod-interface-pdel.sh
+source kubectl-pod-interface-pex.sh
+source kubectl-pod-interface-plg.sh
+source kubectl-pod-interface-pof.sh
+source pod.sh
+source namespace.sh
+
 # We do this so the called script name variable is avilable in utility functions
 # below, in case of name change, brew alias, etc.
 SCRIPT=`basename ${BASH_SOURCE[0]}`
 
 usage() {
-  cat <<EOF
+cat <<EOF
 ${SCRIPT}(1)
 
 NAME
-    ${SCRIPT} - kubectl pod-interface is a fun, quick, 1-command, pod utility interactive kubectl plugin which wraps kubectl commands, to help you easily interact with your running kubernetes pods
+    kubectl pod-interface
 
 REQUIRES
     kubectl(1)
 
 SYNOPSIS
-    ${SCRIPT} [command] [OPTIONS]
+    $ kubectl pod-interface [pdel|pex|plg|pof] [OPTIONS]
 
 DESCRIPTION
-    kubectl {SCRIPT} is a fun, quick, 1-command, pod utility interactive kubectl plugin which wraps kubectl commands, to help you easily interact with your running kubernetes pods
+    kubectl pod-interface is a fun, quick, 1-command, pod utility interactive kubectl plugin which wraps kubectl commands, to help you easily interact with your running kubernetes pods.
 
+Usage
+    # 1. pex: quick, 1-command, interactive, Kubernetes pod exec utility
+    # get a shell to a running Container.
+    $ kubectl pod-interface pex [option]
 
-  # 1. pex: quick, 1-command, interactive, Kubernetes pod exec utility
-  # get a shell to a running Container.
-  $ kubectl {SCRIPT} pex
+    # 2. pof: quick, 1-command, interactive, Kubernetes pod port-forward utility
+    # forward local port to a running pod.
+    $ kubectl pod-interface pof [option]
 
-  # 2. pof: quick, 1-command, interactive, Kubernetes pod port-forward utility
-  # forward local port to a running pod.
-  $ kubectl {SCRIPT} pof
+    # 3. pdl : quick, 1-command, interactive, Kubernetes pod deletion utility
+    # delete running pod.
+    $ kubectl pod-interface pdel [option]
 
-  # 3. pdl : quick, 1-command, interactive, Kubernetes pod deletion utility
-  # delete running pod.
-  $ kubectl {SCRIPT} pdel
+    # 4. plg : quick, 1-command, interactive, Kubernetes pod logs utility
+    # print the logs for a container in a pod.
+    $ kubectl pod-interface plog [option]
 
-  # 4. plg : quick, 1-command, interactive, Kubernetes pod logs utility
-  # print the logs for a container in a pod.
-  $ kubectl {SCRIPT} plog
-
-  # 5. pcp : quick, 1-command, interactive, Kubernetes pod copy files utility
-  # securely copy files from a container in a pod to your local machine.
-  $ kubectl {SCRIPT} pcp
-
-  # 6. pcpl : quick, 1-command, interactive, Kubernetes pod copy files utility
-  # securely copy files from you
 
 OPTIONS
     -h, --help
         Show this help message
     -f, --force
-        `kud -f` will delete the first pod in the namespace without further prompting.
+        `kubectl pod-interface pdel -f` will delete the first pod in the namespace without further prompting.
     -a, --all
         Delete all pods in the namespace
 
@@ -77,170 +92,208 @@ EOF
 }
 
 # $ kubectl pod-interface pdel [option] 
+function pdel() {
 
-# Transform long options to short ones. Sick trick.
-# http://stackoverflow.com/a/30026641/4096495
-for arg in "$@"; do
-  shift
-  case "$arg" in
-    "--help")       set -- "$@" "-h" ;;
-    "--all")        set -- "$@" "-a" ;;
-    "--force")      set -- "$@" "-f" ;;
-    *)              set -- "$@" "$arg"
-  esac
-done
+    # Transform long options to short ones. Sick trick.
+    # http://stackoverflow.com/a/30026641/4096495
+    for arg in "$2"; do
+      shift
+      case "$arg" in
+        "--help")       set -- "$@" "-h" ;;
+        "--all")        set -- "$@" "-a" ;;
+        "--force")      set -- "$@" "-f" ;;
+        *)              set -- "$@" "$arg"
+      esac
+    done
 
-while getopts :haf OPT; do
-  case $OPT in
-    h ) HELP=true;;
-    a ) ALL=true;;
-    f ) FORCE=true;;
-    \?) echo "Unknown option: -$OPTARG" >&2; exit 1;;
-    : ) echo "Missing option argument for -$OPTARG" >&2; exit 1;;
-  esac
-done
-shift $((OPTIND-1))
+    while getopts :haf OPT; do
+      case $OPT in
+        h ) HELP=true;;
+        a ) ALL=true;;
+        f ) FORCE=true;;
+        \?) echo "Unknown option: -$OPTARG" >&2; exit 1;;
+        : ) echo "Missing option argument for -$OPTARG" >&2; exit 1;;
+      esac
+    done
+    shift $((OPTIND-1))
 
-# Usage, list, and delete should not happen simultaneously, so elif.
-if [[ ${HELP:-} == 'true' ]]; then
-  usage; exit 0
-  else
-    if [[ ${FORCE:-} == 'true' ]]; then
-    po_del_force; exit 0
-    else
-      if [[ ${ALL:-} == 'true' ]]; then
-      po_del_all; exit 0
+    # Usage, list, and delete should not happen simultaneously, so elif.
+    if [[ ${HELP:-} == 'true' ]]; then
+      usage; exit 0
       else
-        ns=$(ns_current)
-        echo "Namespace? (default ${ns:-default}):"; ns_number_list; read NS;
-        echo 'Pod number? (default 1):'; po_number_list; read POD;
-        # Might want to use the negated form: 
-        # https://stackoverflow.com/questions/1885525/how-do-i-prompt-a-user-for-confirmation-in-bash-script
-        read -p "Are you sure? " -n 1 -r
-        echo    # (optional) move to a new line
-        if [[ $REPLY =~ ^[Yy]$ ]]; then
-            po_del
+        if [[ ${FORCE:-} == 'true' ]]; then
+        po_del_force; exit 0
+        else
+          if [[ ${ALL:-} == 'true' ]]; then
+          po_del_all; exit 0
+          else
+            ns=$(ns_current)
+            echo "Namespace? (default ${ns:-default}):"; ns_number_list; read NS;
+            echo 'Pod number? (default 1):'; po_number_list; read POD;
+            # Might want to use the negated form: 
+            # https://stackoverflow.com/questions/1885525/how-do-i-prompt-a-user-for-confirmation-in-bash-script
+            read -p "Are you sure? " -n 1 -r
+            echo    # (optional) move to a new line
+            if [[ $REPLY =~ ^[Yy]$ ]]; then
+                po_del
+              fi
           fi
-      fi
+        fi
     fi
-fi
+
+} 
+
 
 # pex: $ kubectl pod-interface pex [option]
 
-# Transform long options to short ones. Sick trick.
-# http://stackoverflow.com/a/30026641/4096495
-for arg in "$@"; do
-  shift
-  case "$arg" in
-    "--help")       set -- "$@" "-h" ;;
-    *)              set -- "$@" "$arg"
-  esac
-done
+function pex() {
+    # Transform long options to short ones. Sick trick.
+    # http://stackoverflow.com/a/30026641/4096495
+    for arg in "$2"; do
+      shift
+      case "$arg" in
+        "--help")       set -- "$@" "-h" ;;
+        *)              set -- "$@" "$arg"
+      esac
+    done
 
-while getopts :h OPT; do
-  case $OPT in
-    h ) HELP=true;;
-    \?) echo "Unknown option: -$OPTARG" >&2; exit 1;;
-    : ) echo "Missing option argument for -$OPTARG" >&2; exit 1;;
-  esac
-done
-shift $((OPTIND-1))
+    while getopts :h OPT; do
+      case $OPT in
+        h ) HELP=true;;
+        \?) echo "Unknown option: -$OPTARG" >&2; exit 1;;
+        : ) echo "Missing option argument for -$OPTARG" >&2; exit 1;;
+      esac
+    done
+    shift $((OPTIND-1))
 
-# Usage, list, and exec should not happen simultaneously, so elif.
-if [[ ${HELP:-} == 'true' ]]; then
-  usage; exit 0
-else
-  ns=$(ns_current)
-  echo "Namespace? (default ${ns:-default}):"; ns_number_list; read NS;
-  echo 'Pod number? (default 1):'; po_number_list; read POD;
-  if [[ $(con_count) -gt 1 ]]; then
-    echo 'Container number? (default 1):'; con_number_list; read CON;
-    echo 'Command? (default bash)'; IFS= read COMMAND;
-    po_exec_con; exit 0
-  fi
-  echo 'Command? (default bash)'; IFS= read COMMAND;
-  po_exec
-fi
+    # Usage, list, and exec should not happen simultaneously, so elif.
+    if [[ ${HELP:-} == 'true' ]]; then
+      usage; exit 0
+    else
+      ns=$(ns_current)
+      echo "Namespace? (default ${ns:-default}):"; ns_number_list; read NS;
+      echo 'Pod number? (default 1):'; po_number_list; read POD;
+      if [[ $(con_count) -gt 1 ]]; then
+        echo 'Container number? (default 1):'; con_number_list; read CON;
+        echo 'Command? (default bash)'; IFS= read COMMAND;
+        po_exec_con; exit 0
+      fi
+      echo 'Command? (default bash)'; IFS= read COMMAND;
+      po_exec
+    fi
+}
+
 
 # plg: $ kubectl pod-interface plg [option]
 
-# Transform long options to short ones. Sick trick.
-# http://stackoverflow.com/a/30026641/4096495
-for arg in "$@"; do
-  shift
-  case "$arg" in
-    "--help")       set -- "$@" "-h" ;;
-    "--follow")     set -- "$@" "-f" ;;
-    *)              set -- "$@" "$arg"
-  esac
-done
+function plg() {
 
-while getopts :hf OPT; do
-  case $OPT in
-    h ) HELP=true;;
-    f ) FOLLOW=true;;
-    \?) echo "Unknown option: -$OPTARG" >&2; exit 1;;
-    : ) echo "Missing option argument for -$OPTARG" >&2; exit 1;;
-  esac
-done
-shift $((OPTIND-1))
+    # Transform long options to short ones. Sick trick.
+    # http://stackoverflow.com/a/30026641/4096495
+    for arg in "$2"; do
+      shift
+      case "$arg" in
+        "--help")       set -- "$@" "-h" ;;
+        "--follow")     set -- "$@" "-f" ;;
+        *)              set -- "$@" "$arg"
+      esac
+    done
 
-# Usage and log should not happen simultaneously, so elif.
-if [[ ${HELP:-} == 'true' ]]; then
-  usage; exit 0
-else
-  ns=$(ns_current)
-  echo "Namespace? (default ${ns:-default}):"; ns_number_list; read NS;
-  echo 'Pod number? (default 1):'; po_number_list; read POD;
+    while getopts :hf OPT; do
+      case $OPT in
+        h ) HELP=true;;
+        f ) FOLLOW=true;;
+        \?) echo "Unknown option: -$OPTARG" >&2; exit 1;;
+        : ) echo "Missing option argument for -$OPTARG" >&2; exit 1;;
+      esac
+    done
+    shift $((OPTIND-1))
 
-  if [[ $(con_count) -gt 1 ]]; then
-    echo 'Container number? (default 1):'; con_number_list; read CON;
-    if [[ $(po_log | wc -c) -eq 0 ]]; then
-     echo "The selected container has no logs."; exit 0
+    # Usage and log should not happen simultaneously, so elif.
+    if [[ ${HELP:-} == 'true' ]]; then
+      usage; exit 0
+    else
+      ns=$(ns_current)
+      echo "Namespace? (default ${ns:-default}):"; ns_number_list; read NS;
+      echo 'Pod number? (default 1):'; po_number_list; read POD;
+
+      if [[ $(con_count) -gt 1 ]]; then
+        echo 'Container number? (default 1):'; con_number_list; read CON;
+        if [[ $(po_log | wc -c) -eq 0 ]]; then
+        echo "The selected container has no logs."; exit 0
+        fi
+      fi
+      po_log_follow; exit 0
     fi
-  fi
-  po_log_follow; exit 0
-fi
+}
 
 # pof: kubectl pod-interface pof [option]
 
-# Transform long options to short ones. Sick trick.
-# http://stackoverflow.com/a/30026641/4096495
-for arg in "$@"; do
-  shift
-  case "$arg" in
-    "--help")       set -- "$@" "-h" ;;
-    "--port")       set -- "$@" "-p" ;;
-    "--daemon")     set -- "$@" "-d" ;;
-    "--killd")      set -- "$@" "-k" ;;
-    "--killd-all")  set -- "$@" "-a" ;;
-    *)              set -- "$@" "$arg"
-  esac
-done
+function pof() {
+    # Transform long options to short ones. Sick trick.
+    # http://stackoverflow.com/a/30026641/4096495
+    for arg in "$2"; do
+      shift
+      case "$arg" in
+        "--help")       set -- "$@" "-h" ;;
+        "--port")       set -- "$@" "-p" ;;
+        "--daemon")     set -- "$@" "-d" ;;
+        "--killd")      set -- "$@" "-k" ;;
+        "--killd-all")  set -- "$@" "-a" ;;
+        *)              set -- "$@" "$arg"
+      esac
+    done
 
-while getopts :hdka OPT; do
-  case $OPT in
-    h ) HELP=true;;
-    d ) DAEMON=true;;
-    k ) KILLD=true;;
-    a ) KILLDALL=true;;
-    \?) echo "Unknown option: -$OPTARG" >&2; exit 1;;
-    : ) echo "Missing option argument for -$OPTARG" >&2; exit 1;;
-  esac
-done
-shift $((OPTIND-1))
+    while getopts :hdka OPT; do
+      case $OPT in
+        h ) HELP=true;;
+        d ) DAEMON=true;;
+        k ) KILLD=true;;
+        a ) KILLDALL=true;;
+        \?) echo "Unknown option: -$OPTARG" >&2; exit 1;;
+        : ) echo "Missing option argument for -$OPTARG" >&2; exit 1;;
+      esac
+    done
+    shift $((OPTIND-1))
 
-# Help and port-forward should not happen simultaneously, so elif.
-if [[ ${HELP:-} == 'true' ]]; then
-  usage; exit 0
-elif [[ ${KILLDALL:-} == 'true' ]]; then
-  killdall; exit 0
-else
-  initappdir
-  ns=$(ns_current)
-  ctx=$(cur_ctx)
-  echo "Cluster? (default ${ctx:-default}):"; ctx_number_list; read CTX;
-  echo "Namespace? (default ${ns:-default}):"; ns_number_list; read NS;
-  echo 'Pod number? (default 1):'; po_number_list; read POD;
-  po_pf_all
-fi
+    # Help and port-forward should not happen simultaneously, so elif.
+    if [[ ${HELP:-} == 'true' ]]; then
+      usage; exit 0
+    elif [[ ${KILLDALL:-} == 'true' ]]; then
+      killdall; exit 0
+    else
+      initappdir
+      ns=$(ns_current)
+      ctx=$(cur_ctx)
+      echo "Cluster? (default ${ctx:-default}):"; ctx_number_list; read CTX;
+      echo "Namespace? (default ${ns:-default}):"; ns_number_list; read NS;
+      echo 'Pod number? (default 1):'; po_number_list; read POD;
+      po_pf_all
+    fi
+
+}
+
+function main() {
+
+  opt="$1"
+  if [[ "${opt}" == 'pof' ]]; then
+      pof
+
+  elif [[ "${opt}" == 'del' ]]; then
+      del 
+
+  elif [[ "${opt}" == 'pex' ]]; then
+      pex
+
+  elif [[ "${opt}" == 'plg' ]]; then
+      plg
+
+  else
+    echo "${opt} option is not available. Check the command usage"
+    usage; 
+    exit 0
+  fi
+
+}
+
+main "$@"
