strat building func core

diff --git a/bin/kubectl-pod-interface b/bin/kubectl-pod-interface
--- a/bin/kubectl-pod-interface
+++ b/bin/kubectl-pod-interface
@@ -126,3 +126,122 @@ if [[ ${HELP:-} == 'true' ]]; then
     fi
 fi
 
+# pex: $ kubectl pod-interface pex [option]
+
+# Transform long options to short ones. Sick trick.
+# http://stackoverflow.com/a/30026641/4096495
+for arg in "$@"; do
+  shift
+  case "$arg" in
+    "--help")       set -- "$@" "-h" ;;
+    *)              set -- "$@" "$arg"
+  esac
+done
+
+while getopts :h OPT; do
+  case $OPT in
+    h ) HELP=true;;
+    \?) echo "Unknown option: -$OPTARG" >&2; exit 1;;
+    : ) echo "Missing option argument for -$OPTARG" >&2; exit 1;;
+  esac
+done
+shift $((OPTIND-1))
+
+# Usage, list, and exec should not happen simultaneously, so elif.
+if [[ ${HELP:-} == 'true' ]]; then
+  usage; exit 0
+else
+  ns=$(ns_current)
+  echo "Namespace? (default ${ns:-default}):"; ns_number_list; read NS;
+  echo 'Pod number? (default 1):'; po_number_list; read POD;
+  if [[ $(con_count) -gt 1 ]]; then
+    echo 'Container number? (default 1):'; con_number_list; read CON;
+    echo 'Command? (default bash)'; IFS= read COMMAND;
+    po_exec_con; exit 0
+  fi
+  echo 'Command? (default bash)'; IFS= read COMMAND;
+  po_exec
+fi
+
+# plg: $ kubectl pod-interface plg [option]
+
+# Transform long options to short ones. Sick trick.
+# http://stackoverflow.com/a/30026641/4096495
+for arg in "$@"; do
+  shift
+  case "$arg" in
+    "--help")       set -- "$@" "-h" ;;
+    "--follow")     set -- "$@" "-f" ;;
+    *)              set -- "$@" "$arg"
+  esac
+done
+
+while getopts :hf OPT; do
+  case $OPT in
+    h ) HELP=true;;
+    f ) FOLLOW=true;;
+    \?) echo "Unknown option: -$OPTARG" >&2; exit 1;;
+    : ) echo "Missing option argument for -$OPTARG" >&2; exit 1;;
+  esac
+done
+shift $((OPTIND-1))
+
+# Usage and log should not happen simultaneously, so elif.
+if [[ ${HELP:-} == 'true' ]]; then
+  usage; exit 0
+else
+  ns=$(ns_current)
+  echo "Namespace? (default ${ns:-default}):"; ns_number_list; read NS;
+  echo 'Pod number? (default 1):'; po_number_list; read POD;
+
+  if [[ $(con_count) -gt 1 ]]; then
+    echo 'Container number? (default 1):'; con_number_list; read CON;
+    if [[ $(po_log | wc -c) -eq 0 ]]; then
+     echo "The selected container has no logs."; exit 0
+    fi
+  fi
+  po_log_follow; exit 0
+fi
+
+# pof: kubectl pod-interface pof [option]
+
+# Transform long options to short ones. Sick trick.
+# http://stackoverflow.com/a/30026641/4096495
+for arg in "$@"; do
+  shift
+  case "$arg" in
+    "--help")       set -- "$@" "-h" ;;
+    "--port")       set -- "$@" "-p" ;;
+    "--daemon")     set -- "$@" "-d" ;;
+    "--killd")      set -- "$@" "-k" ;;
+    "--killd-all")  set -- "$@" "-a" ;;
+    *)              set -- "$@" "$arg"
+  esac
+done
+
+while getopts :hdka OPT; do
+  case $OPT in
+    h ) HELP=true;;
+    d ) DAEMON=true;;
+    k ) KILLD=true;;
+    a ) KILLDALL=true;;
+    \?) echo "Unknown option: -$OPTARG" >&2; exit 1;;
+    : ) echo "Missing option argument for -$OPTARG" >&2; exit 1;;
+  esac
+done
+shift $((OPTIND-1))
+
+# Help and port-forward should not happen simultaneously, so elif.
+if [[ ${HELP:-} == 'true' ]]; then
+  usage; exit 0
+elif [[ ${KILLDALL:-} == 'true' ]]; then
+  killdall; exit 0
+else
+  initappdir
+  ns=$(ns_current)
+  ctx=$(cur_ctx)
+  echo "Cluster? (default ${ctx:-default}):"; ctx_number_list; read CTX;
+  echo "Namespace? (default ${ns:-default}):"; ns_number_list; read NS;
+  echo 'Pod number? (default 1):'; po_number_list; read POD;
+  po_pf_all
+fi
